version: "3"
services:
  influxdb:
    image: influxdb:2.7.6
    container_name: influxdb
    networks:
      - common_network
    ports:
      - "8086:8086"
    env_file:
      - influxdb.env
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - shared-data:/shared
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - common_network
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/local_dashboards:/var/lib/grafana/dashboards/local
    restart: unless-stopped
  
  node-red:
    image: nodered/node-red:4.0.2-debian
    container_name: node-red
    build:
      context: .
      dockerfile: "node-red/Dockerfile"
    ports:
      - "1880:1880"
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - "./node-red/data:/data"
    networks:
      - common_network
    environment: 
      - TZ=UTC+1
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    build:
      context: .
      dockerfile: "mosquitto/Dockerfile"
    container_name: mosquitto
    networks:
      - common_network
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto"
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    env_file:
      - "mosquitto.env"
    restart: unless-stopped

  emqx:
    image: emqx/emqx:5.3.2
    container_name: emqx
    networks:
      - common_network
    ports:
      - "1884:1883"   # MQTT port (changed to avoid conflict with Mosquitto)
      - "8083:8083"   # MQTT over WebSocket port
      - "8084:8084"   # MQTT over WSS port
      - "8081:8081"   # HTTP API port
      - "18083:18083" # Dashboard port
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    env_file:
      - emqx.env
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - common_network
    ports:
      - "3306:3306"
    env_file:
      - mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - common_network
    ports:
      - "8000:8000"
      - "9000:9000"
    env_file:
      - portainer.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped

networks:
  common_network:
    name: docker-influxdb-grafana-nodered-mqtt_common_network

volumes:
  influxdb-data:
  grafana-data:      
  node-red-data:
  mosquitto-data:
  shared-data:
  emqx-data:
  emqx-log:
  mysql-data:
  portainer-data: