version: "3"
services: 
  influxdb:
    image: influxdb:2.7.6
    container_name: influxdb
    networks:
      - common_network
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=eeyae8@nottingham.ac.uk
      - DOCKER_INFLUXDB_INIT_PASSWORD=fortknox123
      - DOCKER_INFLUXDB_INIT_ORG=IoT Project
      - DOCKER_INFLUXDB_INIT_BUCKET=IoT
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Pmouy_Yw9IIwIM7UpQc_rd0o2STHzjgqZTMm-yQMBcJxrBWWONfMrvoY0gurSOcAbAtLAeIQl0zSJyc-VRqrzQ==
      - DOCKER_INFLUXDB_INIT_RETENTION=0
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - shared-data:/shared
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - common_network
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    volumes:
      - "grafana-data:/var/lib/grafana"
    restart: unless-stopped
  
  node-red:
    image: nodered/node-red:4.0.2-debian
    container_name: node-red
    build:
      context: .
      dockerfile: "node-red/Dockerfile"
    ports:
      - "1880:1880"
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - "./node-red/data:/data"
    networks:
      - common_network
    environment: 
      - TZ=UTC+1
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    build:
      context: .
      dockerfile: "mosquitto/Dockerfile"
    container_name: mosquitto
    networks:
      - common_network
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto"
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    env_file:
      - "mosquitto.env"
    restart: unless-stopped


networks:
  common_network:
    name: docker-influxdb-grafana-nodered-mqtt_common_network


volumes:
  influxdb-data:
  grafana-data:        
  node-red-data:
  mosquitto-data:
  shared-data:


