apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: "IoT Project"
      defaultBucket: "IoT"
    secureJsonData:
      token: "Pmouy_Yw9IIwIM7UpQc_rd0o2STHzjgqZTMm-yQMBcJxrBWWONfMrvoY0gurSOcAbAtLAeIQl0zSJyc-VRqrzQ=="